app_default_index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET

app_default_photos:
    path:
        pt_BR: /{_locale}/fotos
        en: /{_locale}/photos
    controller: App\Controller\DefaultController::photos
    methods: GET
    requirements:
        _locale: pt_BR|en
        
app_login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: GET|POST 
    
app_logout:
    path: /logout
    methods: GET